import BootstrapClient from "../components/BootstrapClient";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";


export const metadata = {
  title: "React Restaurant",
  description: "Generated by Tanner90909",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">{children}
      <BootstrapClient />
      </body>
    </html>
  );
}
